[build]
	command = "# no build command"
	functions = "netlify/functions"
	publish = "public"


[dev]
  # Local dev command. A.k.a npm start
  command = "react-scripts start"
  
[functions]
  node_bundler = "esbuild"